spring:
  application:
    name: com-peppers-exam
  jpa:
    properties:
      hibernate:
        session_factory:
        #org.hibernate.EmptyInterceptor类的拓展
        #          interceptor: com.yyc.ycloud.bc.data.authority.jpa.handler.JpaDataAuthorityHandler
        #org.hibernate.resource.jdbc.spi.StatementInspector的sql拦截
    #          statement_inspector: com.yyc.ycloud.bc.data.authority.jpa.handler.JpaDataAuthorityHandler
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/person-exam?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zhaoyu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5  #最小空闲连接数量
      idle-timeout: 180000 #空间链接存活最大时间，默认600000(10分钟)
      maximum-pool-size: 10 #链接池最大链接数，默认是10
      auto-commit: true #这个属性控制从池返回的连接的默认自动提交行为，默认true
      pool-name: MyHikariCP # 数据源链接池名称
      max-lifetime: 900000 #这个属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库链接超时时间，默认30秒，即30000

server:
  port: 11111

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


  com:
    zaxxer:
      hikari:
        HikariConfig: DEBUG
spring.jackson.time-zone: GMT+8